[package]
name = "simrpg"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.13.2"
bevy_simple_tilemap = "0.14.0"
ndarray = "0.15.6"
pathfinding = "4.9.1"
rand = "0.8.5"

[workspace]
resolver = "2"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
