[package]
name = "bevy-pathfinding-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.13.2"

[workspace]
resolver = "2"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
